name: Build and Deploy (Dispatch)
on:
 push:
   branches:
     - master

jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Build npm
        run: |
          yarn
          yarn run build
  RepoAjobs:
    runs-on: [ubuntu-latest]
    needs: Build
    steps:
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEVOPS_TOKEN  }}
          repository: ${{ secrets.dispatch_repo }}
          event-type: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.actor }}
          client-payload: >-
            {
              "type": "docker",
              "repository": "${{ github.event.repository.name }}" ,
              "repository_full": "${{ github.event.repository.full_name }}" ,
              "github-actor": "${{ github.actor }}",
              "github-sha": "${{ github.sha }}",
              "github-ref": "${{ github.ref }}"
            }
